// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ip_event.proto

package com.mohammad.ipevents.model;

public final class IpEvents {
  private IpEvents() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IpEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lookout.backend_coding_questions.q1.IpEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * A unique SHA256 hash of an app, used as a unique ID for the app
     * </pre>
     *
     * <code>required string app_sha256 = 1;</code>
     * @return Whether the appSha256 field is set.
     */
    boolean hasAppSha256();
    /**
     * <pre>
     * A unique SHA256 hash of an app, used as a unique ID for the app
     * </pre>
     *
     * <code>required string app_sha256 = 1;</code>
     * @return The appSha256.
     */
    java.lang.String getAppSha256();
    /**
     * <pre>
     * A unique SHA256 hash of an app, used as a unique ID for the app
     * </pre>
     *
     * <code>required string app_sha256 = 1;</code>
     * @return The bytes for appSha256.
     */
    com.google.protobuf.ByteString
        getAppSha256Bytes();

    /**
     * <pre>
     * A single IPV4 address that an app has connected to.
     * </pre>
     *
     * <code>required int64 ip = 2;</code>
     * @return Whether the ip field is set.
     */
    boolean hasIp();
    /**
     * <pre>
     * A single IPV4 address that an app has connected to.
     * </pre>
     *
     * <code>required int64 ip = 2;</code>
     * @return The ip.
     */
    long getIp();
  }
  /**
   * Protobuf type {@code lookout.backend_coding_questions.q1.IpEvent}
   */
  public static final class IpEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lookout.backend_coding_questions.q1.IpEvent)
      IpEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IpEvent.newBuilder() to construct.
    private IpEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IpEvent() {
      appSha256_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IpEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IpEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              appSha256_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ip_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mohammad.ipevents.model.IpEvents.internal_static_lookout_backend_coding_questions_q1_IpEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mohammad.ipevents.model.IpEvents.internal_static_lookout_backend_coding_questions_q1_IpEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mohammad.ipevents.model.IpEvents.IpEvent.class, com.mohammad.ipevents.model.IpEvents.IpEvent.Builder.class);
    }

    private int bitField0_;
    public static final int APP_SHA256_FIELD_NUMBER = 1;
    private volatile java.lang.Object appSha256_;
    /**
     * <pre>
     * A unique SHA256 hash of an app, used as a unique ID for the app
     * </pre>
     *
     * <code>required string app_sha256 = 1;</code>
     * @return Whether the appSha256 field is set.
     */
    @java.lang.Override
    public boolean hasAppSha256() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * A unique SHA256 hash of an app, used as a unique ID for the app
     * </pre>
     *
     * <code>required string app_sha256 = 1;</code>
     * @return The appSha256.
     */
    @java.lang.Override
    public java.lang.String getAppSha256() {
      java.lang.Object ref = appSha256_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appSha256_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * A unique SHA256 hash of an app, used as a unique ID for the app
     * </pre>
     *
     * <code>required string app_sha256 = 1;</code>
     * @return The bytes for appSha256.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppSha256Bytes() {
      java.lang.Object ref = appSha256_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appSha256_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 2;
    private long ip_;
    /**
     * <pre>
     * A single IPV4 address that an app has connected to.
     * </pre>
     *
     * <code>required int64 ip = 2;</code>
     * @return Whether the ip field is set.
     */
    @java.lang.Override
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * A single IPV4 address that an app has connected to.
     * </pre>
     *
     * <code>required int64 ip = 2;</code>
     * @return The ip.
     */
    @java.lang.Override
    public long getIp() {
      return ip_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAppSha256()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appSha256_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, ip_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appSha256_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, ip_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mohammad.ipevents.model.IpEvents.IpEvent)) {
        return super.equals(obj);
      }
      com.mohammad.ipevents.model.IpEvents.IpEvent other = (com.mohammad.ipevents.model.IpEvents.IpEvent) obj;

      if (hasAppSha256() != other.hasAppSha256()) return false;
      if (hasAppSha256()) {
        if (!getAppSha256()
            .equals(other.getAppSha256())) return false;
      }
      if (hasIp() != other.hasIp()) return false;
      if (hasIp()) {
        if (getIp()
            != other.getIp()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAppSha256()) {
        hash = (37 * hash) + APP_SHA256_FIELD_NUMBER;
        hash = (53 * hash) + getAppSha256().hashCode();
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getIp());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mohammad.ipevents.model.IpEvents.IpEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mohammad.ipevents.model.IpEvents.IpEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lookout.backend_coding_questions.q1.IpEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lookout.backend_coding_questions.q1.IpEvent)
        com.mohammad.ipevents.model.IpEvents.IpEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mohammad.ipevents.model.IpEvents.internal_static_lookout_backend_coding_questions_q1_IpEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mohammad.ipevents.model.IpEvents.internal_static_lookout_backend_coding_questions_q1_IpEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mohammad.ipevents.model.IpEvents.IpEvent.class, com.mohammad.ipevents.model.IpEvents.IpEvent.Builder.class);
      }

      // Construct using com.mohammad.ipevents.model.IpEvents.IpEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        appSha256_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mohammad.ipevents.model.IpEvents.internal_static_lookout_backend_coding_questions_q1_IpEvent_descriptor;
      }

      @java.lang.Override
      public com.mohammad.ipevents.model.IpEvents.IpEvent getDefaultInstanceForType() {
        return com.mohammad.ipevents.model.IpEvents.IpEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.mohammad.ipevents.model.IpEvents.IpEvent build() {
        com.mohammad.ipevents.model.IpEvents.IpEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mohammad.ipevents.model.IpEvents.IpEvent buildPartial() {
        com.mohammad.ipevents.model.IpEvents.IpEvent result = new com.mohammad.ipevents.model.IpEvents.IpEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appSha256_ = appSha256_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ip_ = ip_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mohammad.ipevents.model.IpEvents.IpEvent) {
          return mergeFrom((com.mohammad.ipevents.model.IpEvents.IpEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mohammad.ipevents.model.IpEvents.IpEvent other) {
        if (other == com.mohammad.ipevents.model.IpEvents.IpEvent.getDefaultInstance()) return this;
        if (other.hasAppSha256()) {
          bitField0_ |= 0x00000001;
          appSha256_ = other.appSha256_;
          onChanged();
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAppSha256()) {
          return false;
        }
        if (!hasIp()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mohammad.ipevents.model.IpEvents.IpEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mohammad.ipevents.model.IpEvents.IpEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object appSha256_ = "";
      /**
       * <pre>
       * A unique SHA256 hash of an app, used as a unique ID for the app
       * </pre>
       *
       * <code>required string app_sha256 = 1;</code>
       * @return Whether the appSha256 field is set.
       */
      public boolean hasAppSha256() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * A unique SHA256 hash of an app, used as a unique ID for the app
       * </pre>
       *
       * <code>required string app_sha256 = 1;</code>
       * @return The appSha256.
       */
      public java.lang.String getAppSha256() {
        java.lang.Object ref = appSha256_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appSha256_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A unique SHA256 hash of an app, used as a unique ID for the app
       * </pre>
       *
       * <code>required string app_sha256 = 1;</code>
       * @return The bytes for appSha256.
       */
      public com.google.protobuf.ByteString
          getAppSha256Bytes() {
        java.lang.Object ref = appSha256_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appSha256_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A unique SHA256 hash of an app, used as a unique ID for the app
       * </pre>
       *
       * <code>required string app_sha256 = 1;</code>
       * @param value The appSha256 to set.
       * @return This builder for chaining.
       */
      public Builder setAppSha256(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appSha256_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A unique SHA256 hash of an app, used as a unique ID for the app
       * </pre>
       *
       * <code>required string app_sha256 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppSha256() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appSha256_ = getDefaultInstance().getAppSha256();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A unique SHA256 hash of an app, used as a unique ID for the app
       * </pre>
       *
       * <code>required string app_sha256 = 1;</code>
       * @param value The bytes for appSha256 to set.
       * @return This builder for chaining.
       */
      public Builder setAppSha256Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appSha256_ = value;
        onChanged();
        return this;
      }

      private long ip_ ;
      /**
       * <pre>
       * A single IPV4 address that an app has connected to.
       * </pre>
       *
       * <code>required int64 ip = 2;</code>
       * @return Whether the ip field is set.
       */
      @java.lang.Override
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * A single IPV4 address that an app has connected to.
       * </pre>
       *
       * <code>required int64 ip = 2;</code>
       * @return The ip.
       */
      @java.lang.Override
      public long getIp() {
        return ip_;
      }
      /**
       * <pre>
       * A single IPV4 address that an app has connected to.
       * </pre>
       *
       * <code>required int64 ip = 2;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(long value) {
        bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A single IPV4 address that an app has connected to.
       * </pre>
       *
       * <code>required int64 ip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lookout.backend_coding_questions.q1.IpEvent)
    }

    // @@protoc_insertion_point(class_scope:lookout.backend_coding_questions.q1.IpEvent)
    private static final com.mohammad.ipevents.model.IpEvents.IpEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mohammad.ipevents.model.IpEvents.IpEvent();
    }

    public static com.mohammad.ipevents.model.IpEvents.IpEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IpEvent>
        PARSER = new com.google.protobuf.AbstractParser<IpEvent>() {
      @java.lang.Override
      public IpEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IpEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IpEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IpEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mohammad.ipevents.model.IpEvents.IpEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lookout_backend_coding_questions_q1_IpEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lookout_backend_coding_questions_q1_IpEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ip_event.proto\022#lookout.backend_coding" +
      "_questions.q1\")\n\007IpEvent\022\022\n\napp_sha256\030\001" +
      " \002(\t\022\n\n\002ip\030\002 \002(\003B\'\n\033com.mohammad.ipevent" +
      "s.modelB\010IpEvents"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lookout_backend_coding_questions_q1_IpEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lookout_backend_coding_questions_q1_IpEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lookout_backend_coding_questions_q1_IpEvent_descriptor,
        new java.lang.String[] { "AppSha256", "Ip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
